openapi: 3.0.1
info:
  title: MotiveMinds SAP Connector
  description: SAP Business Partner and Product Management for Microsoft Copilot
  version: 1.0.0

servers:
  - url: https://motiveminds-demo-mcp.onrender.com/mcp

paths:
  /tools/searchCustomerByCustomerDescription:
    post:
      summary: Search SAP Customers
      description: Search for customers in SAP by name or description
      operationId: SearchCustomers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - description
              properties:
                description:
                  type: string
                  description: Customer name to search for
                  x-ms-summary: Customer Name
                search_field:
                  type: string
                  description: Field to search in
                  default: CustomerName
                  x-ms-summary: Search Field
                  enum:
                    - CustomerName
                    - CustomerFullName
                    - Customer
                exact_match:
                  type: boolean
                  description: Use exact match instead of partial search
                  default: false
                  x-ms-summary: Exact Match
                max_results:
                  type: integer
                  description: Maximum number of results
                  default: 10
                  minimum: 1
                  maximum: 50
                  x-ms-summary: Max Results
      responses:
        '200':
          description: Customer search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  found_customers:
                    type: integer
                    description: Number of customers found
                    x-ms-summary: Found Customers
                  customers:
                    type: array
                    description: List of matching customers
                    x-ms-summary: Customer List
                    items:
                      type: object
                      properties:
                        Customer:
                          type: string
                          description: Customer ID
                          x-ms-summary: Customer ID
                        CustomerName:
                          type: string
                          description: Customer name
                          x-ms-summary: Customer Name
                        CustomerFullName:
                          type: string
                          description: Full customer name
                          x-ms-summary: Full Name

  /tools/searchProductByDescription:
    post:
      summary: Search SAP Products
      description: Search for products in SAP by description
      operationId: SearchProducts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: Product description to search for
                  x-ms-summary: Product Description
                language:
                  type: string
                  description: Language code
                  default: EN
                  x-ms-summary: Language
                  enum:
                    - EN
                    - DE
                    - FR
                    - ES
                exact_match:
                  type: boolean
                  description: Use exact match instead of partial search
                  default: false
                  x-ms-summary: Exact Match
                max_results:
                  type: integer
                  description: Maximum number of results
                  default: 10
                  minimum: 1
                  maximum: 50
                  x-ms-summary: Max Results
                product:
                  type: string
                  description: Specific product ID for direct lookup
                  x-ms-summary: Product ID
      responses:
        '200':
          description: Product search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  found_products:
                    type: integer
                    description: Number of products found
                    x-ms-summary: Found Products
                  products:
                    type: array
                    description: List of matching products
                    x-ms-summary: Product List
                    items:
                      type: object
                      properties:
                        Product:
                          type: string
                          description: Product ID
                          x-ms-summary: Product ID
                        ProductDescription:
                          type: string
                          description: Product description
                          x-ms-summary: Description
                        Language:
                          type: string
                          description: Language code
                          x-ms-summary: Language

  /tools/generic_sap_search:
    post:
      summary: Generic SAP Query
      description: Execute custom SAP OData queries
      operationId: GenericSapQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - service_path
              properties:
                service_path:
                  type: string
                  description: SAP service path
                  x-ms-summary: Service Path
                method:
                  type: string
                  description: HTTP method
                  default: GET
                  x-ms-summary: HTTP Method
                  enum:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                params:
                  type: object
                  description: Query parameters as JSON object
                  x-ms-summary: Query Parameters
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: SAP query results
          content:
            application/json:
              schema:
                type: object
                description: Raw SAP response data
                x-ms-summary: SAP Response

  /tools/post_to_sap:
    post:
      summary: Create SAP Record
      description: Create or update records in SAP
      operationId: CreateSapRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - endpoint
                - payload
              properties:
                endpoint:
                  type: string
                  description: SAP endpoint path
                  x-ms-summary: Endpoint
                payload:
                  type: string
                  description: JSON data to send
                  x-ms-summary: Data Payload
                content_type:
                  type: string
                  description: Content type
                  default: application/json
                  x-ms-summary: Content Type
      responses:
        '200':
          description: Operation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    description: HTTP status code
                    x-ms-summary: Status Code
                  status_message:
                    type: string
                    description: Status message
                    x-ms-summary: Status
                  response_data:
                    type: string
                    description: Response from SAP
                    x-ms-summary: SAP Response

  /resources/greeting:
    get:
      summary: Get Greeting
      description: Get a personalized greeting message
      operationId: GetGreeting
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: Name for greeting
          x-ms-summary: Name
      responses:
        '200':
          description: Greeting message
          content:
            text/plain:
              schema:
                type: string
                x-ms-summary: Greeting

components:
  schemas:
    Customer:
      type: object
      properties:
        Customer:
          type: string
          x-ms-summary: Customer ID
        CustomerName:
          type: string
          x-ms-summary: Customer Name
        CustomerFullName:
          type: string
          x-ms-summary: Full Name

    Product:
      type: object
      properties:
        Product:
          type: string
          x-ms-summary: Product ID
        ProductDescription:
          type: string
          x-ms-summary: Description
        Language:
          type: string
          x-ms-summary: Language

    SapResponse:
      type: object
      properties:
        status_code:
          type: integer
          x-ms-summary: Status Code
        status_message:
          type: string
          x-ms-summary: Status
        response_data:
          type: string
          x-ms-summary: Response Data