version: '3.8'

services:
  motiveminds-mcp:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PYTHON_VERSION=3.12
    image: motiveminds-mcp:latest
    container_name: motiveminds-mcp-server
    
    # Port mapping - expose MCP server
    ports:
      - "${PORT:-10000}:10000"
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Additional environment variables
    environment:
      - PORT=10000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    # Health check to ensure service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy for production reliability
    restart: unless-stopped
    
    # Resource limits for optimization
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network configuration
    networks:
      - mcp-network
    
    # Volume mounts for persistence (optional)
    volumes:
      - ./logs:/app/logs:rw
      # Mount .env file explicitly if needed
      - ./.env:/app/.env:ro

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: motiveminds-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      motiveminds-mcp:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mcp-network
    profiles:
      - production

networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  logs:
    driver: local