swagger: '2.0'
info:
  title: MotiveMinds SAP MCP Server
  description: MCP Server for SAP Business Partner and Product Management - provides searchCustomerByCustomerDescription, searchProductByDescription, generic_sap_search, and post_to_sap tools for comprehensive SAP integration
  version: 1.0.0
host: motiveminds-demo-mcp.onrender.com
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: MotiveMinds SAP Integration Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success