openapi: 3.0.1
info:
  title: Goodbaby Product API
  description: API to retrieve product IDs based on product URLs.
  version: 1.0.0
servers:
  - url: https://goodbaby--europe--gmbh---co--kg-dev-familyandfriends-srv.cfapps.eu10-004.hana.ondemand.com/rest

paths:
  /ai/getProductId:
    post:
      summary: Get Product ID
      description: Retrieves a product ID by providing the product URL.
      operationId: getProductId
      security:
        - OAuth2: [uaa.resource]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                URL:
                  type: string
                  example: "https://www.cybex-online.com/en/us/p/cs-pl-cloud-t-sensorsafe-3.html"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                    example: "12345"
        '400':
          description: Invalid request
        '401':
          description: Unauthorized – invalid or expired token
        '500':
          description: Internal server error

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://cbx-dev-enviornment-623550vb.authentication.eu10.hana.ondemand.com/oauth/token
          scopes:
            uaa.resource: Access the Product API
